export const SET_POKEMON = 'SET_POKEMON';
export const SET_ERROR = 'SET_ERROR';
export const CLEAN_ERROR = 'CLEAN_ERROR';
export const SET_LOADING = 'SET_LOADING';
export const FETCH_POKEMON_DETAIL = 'FETCH_POKEMON_DETAIL';
export const SET_FAVORITE_POKEMON = 'SET_FAVORITE_POKEMON';